"""
Django settings for dash project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
import secrets
import sys
from pathlib import Path
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = config("DEBUG", default=False, cast=bool)
SECRET_KEY = config("SECRET_KEY", default=None)


def is_safe_local_command():
    safe_local_commands = {"test", "check", "shell", "migrate", "collectstatic", "runserver"}
    return len(sys.argv) > 1 and sys.argv[1] in safe_local_commands

if SECRET_KEY is None:
    if DEBUG or is_safe_local_command():
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")

ALLOWED_HOSTS = [
    host.strip()
    for host in config("ALLOWED_HOSTS", default="localhost,127.0.0.1,testserver").split(",")
    if host.strip()
]

if 'CODESPACE_NAME' in os.environ:
    codespace_name = config("CODESPACE_NAME")
    codespace_domain = config("GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN")
    CSRF_TRUSTED_ORIGINS = [f'https://{codespace_name}-8000.{codespace_domain}']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_browser_reload",
    "channels",
    "storages",
    "consultancy",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

X_FRAME_OPTIONS = "SAMEORIGIN"

ROOT_URLCONF = "dash.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "dash" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dash.wsgi.application"
ASGI_APPLICATION = "dash.asgi.application"

# Django Channels – Redis channel layer (falls back to in-memory for dev/tests)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": config(
            "CHANNEL_LAYER_BACKEND",
            default="channels.layers.InMemoryChannelLayer",
        ),
        "CONFIG": {
            "hosts": [config("REDIS_URL", default="redis://localhost:6379")],
        }
        if config("CHANNEL_LAYER_BACKEND", default="") == "channels_redis.core.RedisChannelLayer"
        else {},
    }
}


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASE_URL = config("DATABASE_URL", default=None)
if DATABASE_URL:
    try:
        import dj_database_url  # type: ignore[import]
        DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
    except ImportError:
        DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "dash" / "static",
]

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "dash" / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "dash" / "media"

DARAJA_ENVIRONMENT = config("DARAJA_ENVIRONMENT", default="sandbox")
DARAJA_SHORTCODE = config("DARAJA_SHORTCODE", default="174379")
DARAJA_PASSKEY = config("DARAJA_PASSKEY", default=None)
DARAJA_CALLBACK_URL = config(
    "DARAJA_CALLBACK_URL",
    default="https://example.com/payments/mpesa/callback/",
)
PAYMENT_GATEWAY_NAME = config("PAYMENT_GATEWAY_NAME", default="Stripe")
DARAJA_DEMO_SESSION_REFERENCE = config("DARAJA_DEMO_SESSION_REFERENCE", default="DASH-LEGAL-2048")
DARAJA_DEMO_AMOUNT = config("DARAJA_DEMO_AMOUNT", default=2250, cast=int)
DARAJA_DEMO_PHONE_NUMBER = config("DARAJA_DEMO_PHONE_NUMBER", default="254700123456")

if DARAJA_PASSKEY is None and not DEBUG and not is_safe_local_command():
    raise ImproperlyConfigured("The DARAJA_PASSKEY setting must not be empty.")


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Daraja consumer credentials
DARAJA_CONSUMER_KEY = config("DARAJA_CONSUMER_KEY", default="")
DARAJA_CONSUMER_SECRET = config("DARAJA_CONSUMER_SECRET", default="")

# Subscription fee
PLATFORM_SUBSCRIPTION_FEE = config("PLATFORM_SUBSCRIPTION_FEE", default=400, cast=int)

# S3 / Cloudflare R2 media storage (optional)
USE_S3 = config("USE_S3", default=False, cast=bool)
if USE_S3:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL", default=None)
    AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default=None)
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"

